In [1]:
# Solve AND gate problem using neural network

import numpy as np

# Define the inputs and corresponding labels for the 2-input AND gate
inputs = np.array([[0, 0],
                   [0, 1],
                   [1, 0],
                   [1, 1]])

labels = np.array([0, 0, 0, 1])

# Define the weights and biases for the neural network
weights = np.array([0.5, 0.5])
bias = -0.7

# Define the activation function (step function)
def step_function(x):
    return 0 if x <= 0 else 1

# Perform the forward pass to compute the outputs
outputs = []
for input_row in inputs:
    weighted_sum = np.dot(input_row, weights) + bias
    output = step_function(weighted_sum)
    outputs.append(output)

# Compare the predicted outputs with the actual labels
correct_predictions = np.sum(outputs == labels)

# Print the results
print("Inputs:", inputs)
print("Labels (Actual Outputs):", labels)
print("Predicted Outputs:", outputs)
print("Correct Predictions:", correct_predictions)

Inputs: [[0 0]
 [0 1]
 [1 0]
 [1 1]]
Labels (Actual Outputs): [0 0 0 1]
Predicted Outputs: [0, 0, 0, 1]
Correct Predictions: 4


In [2]:
# AND gate (optimized)

inputs = np.array([[0, 0],
                   [0, 1],
                   [1, 0],
                   [1, 1]])
labels = np.array([0, 0, 0, 1])

weights = np.array([0.5, 0.5])

bias = [-0.7, -0.7, -0.7, -0.7]

def step_function(x, threshold=0):
    return np.where(x <= threshold, 0, 1)

outputs = np.dot(inputs, weights) + bias

final_outputs = step_function(outputs)

correct_predictions = np.sum(final_outputs == labels)

print("Inputs:", inputs)
print("Labels (Actual Outputs):", labels)
print("Predicted Outputs:", final_outputs)
print("Correct Predictions:", correct_predictions)

Inputs: [[0 0]
 [0 1]
 [1 0]
 [1 1]]
Labels (Actual Outputs): [0 0 0 1]
Predicted Outputs: [0 0 0 1]
Correct Predictions: 4


In [3]:
# Define the inputs and corresponding labels for the 2-input AND gate (random weights and biases)

inputs = np.array([[0, 0],
                   [0, 1],
                   [1, 0],
                   [1, 1]])

labels = np.array([0, 0, 0, 1])

# Define the range for random initialization
weight_range = (-1, 1)
bias_range = (-1, 1)

# Randomly initialize the weights and bias within the defined range
weights = np.random.uniform(low=weight_range[0], high=weight_range[1], size=(2,))
bias = np.random.uniform(low=bias_range[0], high=bias_range[1])

# Define the activation function (step function)
def step_function(x):
    return 0 if x <= 0 else 1

# Perform the forward pass to compute the outputs
outputs = []
for input_row in inputs:
    weighted_sum = np.dot(input_row, weights) + bias
    output = step_function(weighted_sum)
    outputs.append(output)

# Compare the predicted outputs with the actual labels
correct_predictions = np.sum(outputs == labels)

# Print the results
print("Random Weights:", weights)
print("Random Bias:", bias)
print("Inputs:", inputs)
print("Labels (Actual Outputs):", labels)
print("Predicted Outputs:", outputs)
print("Correct Predictions:", correct_predictions)

Random Weights: [ 0.14393707 -0.34613412]
Random Bias: -0.9518954987917279
Inputs: [[0 0]
 [0 1]
 [1 0]
 [1 1]]
Labels (Actual Outputs): [0 0 0 1]
Predicted Outputs: [0, 0, 0, 0]
Correct Predictions: 3


In [4]:
# Define the inputs and corresponding labels for the 3-input AND gate

inputs = np.array([[0, 0, 0],
                   [0, 0, 1],
                   [0, 1, 0],
                   [0, 1, 1],
                   [1, 0, 0],
                   [1, 0, 1],
                   [1, 1, 0],
                   [1, 1, 1]])

labels = np.array([0, 0, 0, 0, 0, 0, 0, 1])

# Define the weights and bias for the neural network
weights = np.array([1, 1, 1])
bias = -2.5

# Define the activation function (step function)
def step_function(x):
    return 0 if x <= 0 else 1

# Perform the forward pass to compute the outputs
outputs = []
for input_row in inputs:
    weighted_sum = np.dot(input_row, weights) + bias
    output = step_function(weighted_sum)
    outputs.append(output)

# print(len(labels))

# Compare the predicted outputs with the actual labels
correct_predictions = np.sum(np.array(outputs) == labels)

# Print the results
print("Inputs:", inputs)
print("Labels (Actual Outputs):", labels)
print("Predicted Outputs:", outputs)
print("Correct Predictions:", correct_predictions)

Inputs: [[0 0 0]
 [0 0 1]
 [0 1 0]
 [0 1 1]
 [1 0 0]
 [1 0 1]
 [1 1 0]
 [1 1 1]]
Labels (Actual Outputs): [0 0 0 0 0 0 0 1]
Predicted Outputs: [0, 0, 0, 0, 0, 0, 0, 1]
Correct Predictions: 8


In [5]:
# Solve OR gate problem using neural network

# Define the inputs and corresponding labels for the 2-input OR gate
inputs = np.array([[0, 0],
                   [0, 1],
                   [1, 0],
                   [1, 1]])

labels = np.array([0, 1, 1, 1]) 

# Define the weights and bias for the neural network
weights = np.array([0.5, 0.5]) 
bias = -0.2 

# Define the activation function (step function)
def step_function(x):
    return 0 if x <= 0 else 1

# Perform the forward pass to compute the outputs
outputs = []
for input_row in inputs:
    weighted_sum = np.dot(input_row, weights) + bias
    output = step_function(weighted_sum)
    outputs.append(output)

# Compare the predicted outputs with the actual labels
correct_predictions = np.sum(outputs == labels)

# Print the results
print("Inputs:", inputs)
print("Labels (Actual Outputs):", labels)
print("Predicted Outputs:", outputs)
print("Correct Predictions:", correct_predictions)

Inputs: [[0 0]
 [0 1]
 [1 0]
 [1 1]]
Labels (Actual Outputs): [0 1 1 1]
Predicted Outputs: [0, 1, 1, 1]
Correct Predictions: 4


In [6]:
# OR gate (optimized)

inputs = np.array([[0, 0],
                   [0, 1],
                   [1, 0],
                   [1, 1]])

labels = np.array([0, 1, 1, 1])

weights = np.array([0.5, 0.5])

bias = [-0.2, -0.2, -0.2, -0.2]

def step_function(x, threshold=0):
    return np.where(x <= threshold, 0, 1)

outputs = np.dot(inputs, weights) + bias

final_outputs = step_function(outputs)

correct_predictions = np.sum(final_outputs == labels)

print("Inputs:", inputs)
print("Labels (Actual Outputs):", labels)
print("Predicted Outputs:", final_outputs)
print("Correct Predictions:", correct_predictions)

Inputs: [[0 0]
 [0 1]
 [1 0]
 [1 1]]
Labels (Actual Outputs): [0 1 1 1]
Predicted Outputs: [0 1 1 1]
Correct Predictions: 4


In [7]:
# Define the inputs and corresponding labels for the 2-input OR gate (random weights and biases)

inputs = np.array([[0, 0],
                   [0, 1],
                   [1, 0],
                   [1, 1]])

labels = np.array([0, 1, 1, 1])

# Define the range for random initialization
weight_range = (-1, 1)
bias_range = (-1, 1)

# Randomly initialize the weights and bias within the defined range
weights = np.random.uniform(low=weight_range[0], high=weight_range[1], size=(2,))
bias = np.random.uniform(low=bias_range[0], high=bias_range[1])

# Define the activation function (step function)
def step_function(x):
    return 0 if x <= 0 else 1


# Perform the forward pass to compute the outputs
outputs = []
for input_row in inputs:
    weighted_sum = np.dot(input_row, weights) + bias
    output = step_function(weighted_sum)
    outputs.append(output)

# Compare the predicted outputs with the actual labels
correct_predictions = np.sum(np.array(outputs) == labels)

# Print the results
print("Random Weights:", weights)
print("Random Bias:", bias)
print("Inputs:", inputs)
print("Labels (Actual Outputs):", labels)
print("Predicted Outputs:", outputs)
print("Correct Predictions:", correct_predictions)

Random Weights: [0.98239111 0.15073168]
Random Bias: 0.8176177304563168
Inputs: [[0 0]
 [0 1]
 [1 0]
 [1 1]]
Labels (Actual Outputs): [0 1 1 1]
Predicted Outputs: [1, 1, 1, 1]
Correct Predictions: 3


In [8]:
# Define the inputs and corresponding labels for the 3-input OR gate

inputs = np.array([[0, 0, 0],
                   [0, 0, 1],
                   [0, 1, 0],
                   [0, 1, 1],
                   [1, 0, 0],
                   [1, 0, 1],
                   [1, 1, 0],
                   [1, 1, 1]])

labels = np.array([0, 1, 1, 1, 1, 1, 1, 1])

# Define the weights and bias for the neural network
weights = np.array([1, 1, 1])
bias = -0.5

# Define the activation function (step function)
def step_function(x):
    return 0 if x <= 0 else 1

# Perform the forward pass to compute the outputs
outputs = []
for input_row in inputs:
    weighted_sum = np.dot(input_row, weights) + bias
    output = step_function(weighted_sum)
    outputs.append(output)

# print(len(labels))

# Compare the predicted outputs with the actual labels
correct_predictions = np.sum(np.array(outputs) == labels)

# Print the results
print("Inputs:", inputs)
print("Labels (Actual Outputs):", labels)
print("Predicted Outputs:", outputs)
print("Correct Predictions:", correct_predictions)

Inputs: [[0 0 0]
 [0 0 1]
 [0 1 0]
 [0 1 1]
 [1 0 0]
 [1 0 1]
 [1 1 0]
 [1 1 1]]
Labels (Actual Outputs): [0 1 1 1 1 1 1 1]
Predicted Outputs: [0, 1, 1, 1, 1, 1, 1, 1]
Correct Predictions: 8


In [9]:
# Solve NOT gate problem using neural network

# Define the inputs and corresponding labels for the NOT gate
inputs = np.array([0,
                   1])

labels = np.array([1, 0])

# Define the weight and bias for the neural network
weight = -1
bias = 0.5

# Define the activation function (step function)
def step_function(x):
    return 0 if x <= 0 else 1

# Perform the forward pass to compute the outputs
outputs = []
for input_row in inputs:
    weighted_sum = np.dot(input_row, weight) + bias
    output = step_function(weighted_sum)
    outputs.append(output)

# Compare the predicted outputs with the actual labels
correct_predictions = np.sum(np.array(outputs) == labels)

# Print the results
print("Inputs:", inputs.flatten())
print("Labels (Actual Outputs):", labels)
print("Predicted Outputs:", outputs)
print("Correct Predictions:", correct_predictions)

Inputs: [0 1]
Labels (Actual Outputs): [1 0]
Predicted Outputs: [1, 0]
Correct Predictions: 2


In [10]:
# NOT gate (optimized)

inputs = np.array([[0],
                   [1]])

labels = np.array([1, 0])

weights = np.array([-1])

bias = [0.5]

def step_function(x, threshold=0):
    return np.where(x <= threshold, 0, 1)

outputs = np.dot(inputs, weights) + bias

final_outputs = step_function(outputs)

correct_predictions = np.sum(final_outputs == labels)

print("Inputs:", inputs)
print("Labels (Actual Outputs):", labels)
print("Predicted Outputs:", final_outputs)
print("Correct Predictions:", correct_predictions)

Inputs: [[0]
 [1]]
Labels (Actual Outputs): [1 0]
Predicted Outputs: [1 0]
Correct Predictions: 2


In [11]:
# Define the inputs and corresponding labels for the NOT gate (random weights and biases)

inputs = np.array([[0],
                   [1]])

labels = np.array([1, 0])  # Output for NOT gate: 1 when input is 0, and 0 when input is 1

# Define the range for random initialization
weight_range = (-2, 2)
bias_range = (-1, 1)

# Randomly initialize the weight and bias within the defined range
weight = np.random.uniform(low=weight_range[0], high=weight_range[1])
bias = np.random.uniform(low=bias_range[0], high=bias_range[1])

# Define the activation function (step function)
def step_function(x):
    return 0 if x <= 0 else 1

# Perform the forward pass to compute the outputs
outputs = []
for input_row in inputs:
    weighted_sum = np.dot(input_row, weight) + bias
    output = step_function(weighted_sum)
    outputs.append(output)

# Compare the predicted outputs with the actual labels
correct_predictions = np.sum(np.array(outputs) == labels)

# Print the results
print("Random Weight:", weight)
print("Random Bias:", bias)
print("Inputs:", inputs.flatten())
print("Labels (Actual Outputs):", labels)
print("Predicted Outputs:", outputs)
print("Correct Predictions:", correct_predictions)

Random Weight: 1.717492573023275
Random Bias: -0.8223461154479903
Inputs: [0 1]
Labels (Actual Outputs): [1 0]
Predicted Outputs: [0, 1]
Correct Predictions: 0


In [12]:
# Define the inputs and corresponding labels for the 2-input NAND gate

inputs = np.array([[0, 0],
                   [0, 1],
                   [1, 0],
                   [1, 1]])

labels = np.array([1, 1, 1, 0])

# Define the weights and bias for the neural network
weights = np.array([-0.5, -0.5])
bias = 0.7

# Define the activation function (step function)
def step_function(x):
    return 0 if x <= 0 else 1

# Perform the forward pass to compute the outputs
outputs = []
for input_row in inputs:
    weighted_sum = np.dot(input_row, weights) + bias
    output = step_function(weighted_sum)
    outputs.append(output)

# Compare the predicted outputs with the actual labels
correct_predictions = np.sum(np.array(outputs) == labels)

# Print the results
print("Inputs:", inputs)
print("Labels (Actual Outputs):", labels)
print("Predicted Outputs:", outputs)
print("Correct Predictions:", correct_predictions)

Inputs: [[0 0]
 [0 1]
 [1 0]
 [1 1]]
Labels (Actual Outputs): [1 1 1 0]
Predicted Outputs: [1, 1, 1, 0]
Correct Predictions: 4


In [13]:
# NAND gate (optimized)

inputs = np.array([[0, 0],
                   [0, 1],
                   [1, 0],
                   [1, 1]])

labels = np.array([1, 1, 1, 0])

weights = np.array([-0.5, -0.5])

bias = [0.7, 0.7, 0.7, 0.7]

def step_function(x, threshold=0):
    return np.where(x <= threshold, 0, 1)

outputs = np.dot(inputs, weights) + bias

final_outputs = step_function(outputs)

correct_predictions = np.sum(final_outputs == labels)

print("Inputs:", inputs)
print("Labels (Actual Outputs):", labels)
print("Predicted Outputs:", final_outputs)
print("Correct Predictions:", correct_predictions)

Inputs: [[0 0]
 [0 1]
 [1 0]
 [1 1]]
Labels (Actual Outputs): [1 1 1 0]
Predicted Outputs: [1 1 1 0]
Correct Predictions: 4


In [14]:
# Define the inputs and corresponding labels for the 2-input NAND gate (random weights and biases)
inputs = np.array([[0, 0],
                   [0, 1],
                   [1, 0],
                   [1, 1]])

labels = np.array([1, 1, 1, 0])

# Define the range for random initialization
weight_range = (-1, 1)
bias_range = (-1, 1)

# Randomly initialize the weights and bias within the defined range
weights = np.random.uniform(low=weight_range[0], high=weight_range[1], size=(2,))
bias = np.random.uniform(low=bias_range[0], high=bias_range[1])

# Define the activation function (step function)
def step_function(x):
    return 0 if x <= 0 else 1

# Perform the forward pass to compute the outputs
outputs = []
for input_row in inputs:
    weighted_sum = np.dot(input_row, weights) + bias
    output = step_function(weighted_sum)
    outputs.append(output)

# Compare the predicted outputs with the actual labels
correct_predictions = np.sum(np.array(outputs) == labels)

# Print the results
print("Random Weights:", weights)
print("Random Bias:", bias)
print("Inputs:", inputs)
print("Labels (Actual Outputs):", labels)
print("Predicted Outputs:", outputs)
print("Correct Predictions:", correct_predictions)

Random Weights: [ 0.91391233 -0.84457376]
Random Bias: 0.13566255698183083
Inputs: [[0 0]
 [0 1]
 [1 0]
 [1 1]]
Labels (Actual Outputs): [1 1 1 0]
Predicted Outputs: [1, 0, 1, 1]
Correct Predictions: 2


In [15]:
# Define the inputs and corresponding labels for the 3-input NAND gate
inputs = np.array([[0, 0, 0],
                   [0, 0, 1],
                   [0, 1, 0],
                   [0, 1, 1],
                   [1, 0, 0],
                   [1, 0, 1],
                   [1, 1, 0],
                   [1, 1, 1]])

labels = np.array([1, 1, 1, 1, 1, 1, 1, 0])

# Define the weights and bias for the neural network
weights = np.array([-1, -1, -1])
bias = 2.5

# Define the activation function (step function)
def step_function(x):
    return 0 if x <= 0 else 1

# Perform the forward pass to compute the outputs
outputs = []
for input_row in inputs:
    weighted_sum = np.dot(input_row, weights) + bias
    output = step_function(weighted_sum)
    outputs.append(output)

# Compare the predicted outputs with the actual labels
correct_predictions = np.sum(np.array(outputs) == labels)

# Print the results
print("Inputs:", inputs)
print("Labels (Actual Outputs):", labels)
print("Predicted Outputs:", outputs)
print("Correct Predictions:", correct_predictions)

Inputs: [[0 0 0]
 [0 0 1]
 [0 1 0]
 [0 1 1]
 [1 0 0]
 [1 0 1]
 [1 1 0]
 [1 1 1]]
Labels (Actual Outputs): [1 1 1 1 1 1 1 0]
Predicted Outputs: [1, 1, 1, 1, 1, 1, 1, 0]
Correct Predictions: 8


In [16]:
# Define the inputs and corresponding labels for the 2-input NOR gate
inputs = np.array([[0, 0],
                   [0, 1],
                   [1, 0],
                   [1, 1]])

labels = np.array([1, 0, 0, 0])

# Define the weights and bias for the neural network
weights = np.array([-0.5, -0.5])
bias = 0.5

# Define the activation function (step function)
def step_function(x):
    return 0 if x <= 0 else 1

# Perform the forward pass to compute the outputs
outputs = []
for input_row in inputs:
    weighted_sum = np.dot(input_row, weights) + bias
    output = step_function(weighted_sum)
    outputs.append(output)

# Compare the predicted outputs with the actual labels
correct_predictions = np.sum(np.array(outputs) == labels)

# Print the results
print("Inputs:", inputs)
print("Labels (Actual Outputs):", labels)
print("Predicted Outputs:", outputs)
print("Correct Predictions:", correct_predictions)

Inputs: [[0 0]
 [0 1]
 [1 0]
 [1 1]]
Labels (Actual Outputs): [1 0 0 0]
Predicted Outputs: [1, 0, 0, 0]
Correct Predictions: 4


In [17]:
# NOR gate (optimized)

inputs = np.array([[0, 0],
                   [0, 1],
                   [1, 0],
                   [1, 1]])

labels = np.array([1, 0, 0, 0])

weights = np.array([-0.5, -0.5])

bias = [0.5, 0.5, 0.5, 0.5]

def step_function(x, threshold=0):
    return np.where(x <= threshold, 0, 1)

outputs = np.dot(inputs, weights) + bias

final_outputs = step_function(outputs)

correct_predictions = np.sum(final_outputs == labels)

print("Inputs:", inputs)
print("Labels (Actual Outputs):", labels)
print("Predicted Outputs:", final_outputs)
print("Correct Predictions:", correct_predictions)

Inputs: [[0 0]
 [0 1]
 [1 0]
 [1 1]]
Labels (Actual Outputs): [1 0 0 0]
Predicted Outputs: [1 0 0 0]
Correct Predictions: 4


In [18]:
# Define the inputs and corresponding labels for the 2-input NOR gate (random weights and biases)
inputs = np.array([[0, 0],
                   [0, 1],
                   [1, 0],
                   [1, 1]])

labels = np.array([1, 0, 0, 0])  # Output for NOR gate: 1, 0, 0, 0

# Define the range for random initialization
weight_range = (-1, 1)
bias_range = (-1, 1)

# Randomly initialize the weights and bias within the defined range
weights = np.random.uniform(low=weight_range[0], high=weight_range[1], size=(2,))
bias = np.random.uniform(low=bias_range[0], high=bias_range[1])

# Define the activation function (step function)
def step_function(x):
    return 0 if x <= 0 else 1

# Perform the forward pass to compute the outputs
outputs = []
for input_row in inputs:
    weighted_sum = np.dot(input_row, weights) + bias
    output = step_function(weighted_sum)
    outputs.append(output)

# Compare the predicted outputs with the actual labels
correct_predictions = np.sum(np.array(outputs) == labels)

# Print the results
print("Random Weights:", weights)
print("Random Bias:", bias)
print("Inputs:", inputs)
print("Labels (Actual Outputs):", labels)
print("Predicted Outputs:", outputs)
print("Correct Predictions:", correct_predictions)

Random Weights: [-0.91903916 -0.99665808]
Random Bias: 0.8104960631318261
Inputs: [[0 0]
 [0 1]
 [1 0]
 [1 1]]
Labels (Actual Outputs): [1 0 0 0]
Predicted Outputs: [1, 0, 0, 0]
Correct Predictions: 4


In [19]:
# Define the inputs and corresponding labels for the 3-input NOR gate
inputs = np.array([[0, 0, 0],
                   [0, 0, 1],
                   [0, 1, 0],
                   [0, 1, 1],
                   [1, 0, 0],
                   [1, 0, 1],
                   [1, 1, 0],
                   [1, 1, 1]])

labels = np.array([1, 0, 0, 0, 0, 0, 0, 0])  # Output for NOR gate: 1, 0, 0, 0, 0, 0, 0, 0

# Define the weights and bias for the neural network
weights = np.array([-1, -1, -1])
bias = 0.5

# Define the activation function (step function)
def step_function(x):
    return 0 if x <= 0 else 1

# Perform the forward pass to compute the outputs
outputs = []
for input_row in inputs:
    weighted_sum = np.dot(input_row, weights) + bias
    output = step_function(weighted_sum)
    outputs.append(output)

# Compare the predicted outputs with the actual labels
correct_predictions = np.sum(np.array(outputs) == labels)

# Print the results
print("Inputs:", inputs)
print("Labels (Actual Outputs):", labels)
print("Predicted Outputs:", outputs)
print("Correct Predictions:", correct_predictions)

Inputs: [[0 0 0]
 [0 0 1]
 [0 1 0]
 [0 1 1]
 [1 0 0]
 [1 0 1]
 [1 1 0]
 [1 1 1]]
Labels (Actual Outputs): [1 0 0 0 0 0 0 0]
Predicted Outputs: [1, 0, 0, 0, 0, 0, 0, 0]
Correct Predictions: 8
