In [1]:
# AND, OR, NOT, NAND and NOR gate with the mean square error loss calculation.

import numpy as np

# Sigmoidal activation function
def sigmoid(x):
    return 1 / (1 + np.exp(-x))

# Define the neural network architecture
input_size = 2  # For AND, OR, NAND, NOR gates
hidden_size = 3
output_size = 1

# Initialize weights and biases
np.random.seed(42)  # Set seed for reproducibility
W1 = np.random.randn(input_size, hidden_size)
b1 = np.random.randn(hidden_size)
W2 = np.random.randn(hidden_size, output_size)
b2 = np.random.randn(output_size)

# Define inputs and target outputs for each gate

# AND Gate
x = np.array([[0, 0], [0, 1], [1, 0], [1, 1]])
target = np.array([[0], [0], [0], [1]])

# OR Gate
# x = np.array([[0, 0], [0, 1], [1, 0], [1, 1]])
# target = np.array([[0], [1], [1], [1]])

# NOT Gate
# Note: NOT gate is a single-input gate, so we redefine the input and target
# input_size = 1
# x = np.array([[0], [1]])
# target = np.array([[1], [0]])

# NAND Gate
# x = np.array([[0, 0], [0, 1], [1, 0], [1, 1]])
# target = np.array([[1], [1], [1], [0]])

# NOR Gate
# x = np.array([[0, 0], [0, 1], [1, 0], [1, 1]])
# target = np.array([[1], [0], [0], [0]])

# Forward pass
hidden_layer_output = (np.dot(x, W1) + b1)
output = sigmoid(np.dot(hidden_layer_output, W2) + b2)

# Calculate the loss (using Mean Squared Error)
loss = np.mean((output - target) ** 2)

# Output the result
print("Output:")
print(output)
print("Loss:", loss)

Output:
[[0.72347913]
 [0.88139173]
 [0.72981989]
 [0.8846886 ]]
Loss: 0.4615518032199156


In [2]:
# Calculate loss function and then minimize the error after Nth iterations by adjusting the parameters.

import numpy as np

# Use the sigmoid activation function
def sigmoid(x):
    return 1 / (1 + np.exp(-x))

# Define the loss function (Mean Squared Error)
def loss(predicted, actual):
    return np.mean((predicted - actual) ** 2)

# Neural network architecture
input_size = 2  # For AND, OR, NAND, NOR gates (adjust for NOT gate)
hidden_size = 3
output_size = 1

# Initialize weights and biases
np.random.seed(42)  # Set seed for reproducibility
W1 = np.random.randn(input_size, hidden_size)
b1 = np.random.randn(hidden_size)
W2 = np.random.randn(hidden_size, output_size)
b2 = np.random.randn(output_size)

# Define the input and target outputs for each gate

# AND Gate
x = np.array([[0, 0], [0, 1], [1, 0], [1, 1]])
target = np.array([[0], [0], [0], [1]])

# OR Gate
# x = np.array([[0, 0], [0, 1], [1, 0], [1, 1]])
# target = np.array([[0], [1], [1], [1]])

# NOT Gate
# Note: NOT gate is a single-input gate, so we redefine the input and target
# input_size = 1
# x = np.array([[0], [1]])
# target = np.array([[1], [0]])

# NAND Gate
# x = np.array([[0, 0], [0, 1], [1, 0], [1, 1]])
# target = np.array([[1], [1], [1], [0]])

# NOR Gate
# x = np.array([[0, 0], [0, 1], [1, 0], [1, 1]])
# target = np.array([[1], [0], [0], [0]])

# Variables to track the best loss and associated weights and biases
best_loss = float('inf')
best_W1, best_b1, best_W2, best_b2 = None, None, None, None

# Training loop
for iteration in range(150):
    # Forward pass
    hidden_layer_output = np.dot(x, W1) + b1
    output = sigmoid(np.dot(hidden_layer_output, W2) + b2)

    # Save the final output
    final_output = output

    # Calculate the loss
    current_loss = loss(output, target)

    # Check if we have found a better loss
    if current_loss < best_loss:
        print(f'New weights found, iteration: {iteration}, loss: {current_loss}')
        best_loss = current_loss
        best_W1, best_b1 = W1.copy(), b1.copy()
        best_W2, best_b2 = W2.copy(), b2.copy()
    else:
        # Revert to the previous best weights and biases
        W1, b1 = best_W1.copy(), best_b1.copy()
        W2, b2 = best_W2.copy(), best_b2.copy()

    # Update weights and biases with small random values
    W1 += 0.09 * np.random.randn(input_size, hidden_size)
    b1 += 0.09 * np.random.randn(hidden_size)
    W2 += 0.09 * np.random.randn(hidden_size, output_size)
    b2 += 0.09 * np.random.randn(output_size)

# Print the final output
print("Final Output:")
print(final_output)

New weights found, iteration: 0, loss: 0.4615518032199156
New weights found, iteration: 1, loss: 0.42713333127364583
New weights found, iteration: 2, loss: 0.3740647434413042
New weights found, iteration: 3, loss: 0.3465387490717778
New weights found, iteration: 4, loss: 0.3405710629136633
New weights found, iteration: 5, loss: 0.264994219880896
New weights found, iteration: 6, loss: 0.26135534678742284
New weights found, iteration: 7, loss: 0.22230287164214324
New weights found, iteration: 9, loss: 0.19057120960159563
New weights found, iteration: 10, loss: 0.18087856855100012
New weights found, iteration: 12, loss: 0.17694085416907632
New weights found, iteration: 15, loss: 0.17151249954994946
New weights found, iteration: 18, loss: 0.15978178987523828
New weights found, iteration: 21, loss: 0.13816447431055767
New weights found, iteration: 23, loss: 0.13621886118481583
New weights found, iteration: 24, loss: 0.1360978096603343
New weights found, iteration: 26, loss: 0.12586712996042

In [3]:
# Modify the previous example in such a way that the neural network updates its parameters until the error or loss reaches to 5%.

# Sigmoidal activation function
def sigmoid(x):
    return 1 / (1 + np.exp(-x))

# Loss function: Mean Squared Error
def loss(predicted, actual):
    return np.mean((predicted - actual) ** 2)

# Neural network architecture
input_size = 2  # For AND, OR, NAND, NOR gates (adjust to 1 for NOT gate)
hidden_size = 3
output_size = 1

# Initialize weights and biases
np.random.seed(42)  # Set seed for reproducibility
W1 = np.random.randn(input_size, hidden_size)
b1 = np.random.randn(hidden_size)
W2 = np.random.randn(hidden_size, output_size)
b2 = np.random.randn(output_size)

# Define the input and target outputs for each gate

# AND Gate
x = np.array([[0, 0], [0, 1], [1, 0], [1, 1]])
target = np.array([[0], [0], [0], [1]])

# OR Gate
# x = np.array([[0, 0], [0, 1], [1, 0], [1, 1]])
# target = np.array([[0], [1], [1], [1]])

# NOT Gate
# Note: NOT gate is a single-input gate, so we redefine the input and target
# input_size = 1
# x = np.array([[0], [1]])
# target = np.array([[1], [0]])

# NAND Gate
# x = np.array([[0, 0], [0, 1], [1, 0], [1, 1]])
# target = np.array([[1], [1], [1], [0]])

# NOR Gate
# x = np.array([[0, 0], [0, 1], [1, 0], [1, 1]])
# target = np.array([[1], [0], [0], [0]])

# Variables to track the best loss and associated weights and biases
best_loss = float('inf')
best_W1, best_b1, best_W2, best_b2 = None, None, None, None

# Training loop with stopping criterion
iteration = 0
final_output = None

while best_loss > 0.05:  # Continue until the loss is less than or equal to 5%
    # Forward pass
    hidden_layer_output = np.dot(x, W1) + b1
    output = sigmoid(np.dot(hidden_layer_output, W2) + b2)

    # Save final output
    final_output = output

    # Loss calculation
    current_loss = loss(output, target)

    if current_loss < best_loss:
        print(f'New weights found, iteration: {iteration}, loss: {current_loss}')
        best_loss = current_loss
        best_W1, best_b1 = W1.copy(), b1.copy()
        best_W2, best_b2 = W2.copy(), b2.copy()
    else:
        # Revert to the previous best weights and biases
        W1, b1 = best_W1.copy(), best_b1.copy()
        W2, b2 = best_W2.copy(), best_b2.copy()

    # Update weights with small random values
    W1 += 0.09 * np.random.randn(input_size, hidden_size)
    b1 += 0.09 * np.random.randn(hidden_size)
    W2 += 0.09 * np.random.randn(hidden_size, output_size)
    b2 += 0.09 * np.random.randn(output_size)

    iteration += 1

# Print the final output
print("Final output after training:")
print(final_output)

New weights found, iteration: 0, loss: 0.4615518032199156
New weights found, iteration: 1, loss: 0.42713333127364583
New weights found, iteration: 2, loss: 0.3740647434413042
New weights found, iteration: 3, loss: 0.3465387490717778
New weights found, iteration: 4, loss: 0.3405710629136633
New weights found, iteration: 5, loss: 0.264994219880896
New weights found, iteration: 6, loss: 0.26135534678742284
New weights found, iteration: 7, loss: 0.22230287164214324
New weights found, iteration: 9, loss: 0.19057120960159563
New weights found, iteration: 10, loss: 0.18087856855100012
New weights found, iteration: 12, loss: 0.17694085416907632
New weights found, iteration: 15, loss: 0.17151249954994946
New weights found, iteration: 18, loss: 0.15978178987523828
New weights found, iteration: 21, loss: 0.13816447431055767
New weights found, iteration: 23, loss: 0.13621886118481583
New weights found, iteration: 24, loss: 0.1360978096603343
New weights found, iteration: 26, loss: 0.12586712996042

In [4]:
# Solve AND gate problem using neural network

import numpy as np

# Define the inputs and corresponding labels for the 2-input AND gate
inputs = np.array([[0, 0],
                   [0, 1],
                   [1, 0],
                   [1, 1]])

labels = np.array([0, 0, 0, 1])

# Define the weights and biases for the neural network
weights = np.array([0.5, 0.5])
bias = -0.7

# Define the activation function (step function)
def step_function(x):
    return 0 if x <= 0 else 1

# Perform the forward pass to compute the outputs
outputs = []
for input_row in inputs:
    weighted_sum = np.dot(input_row, weights) + bias
    output = step_function(weighted_sum)
    outputs.append(output)

# Compare the predicted outputs with the actual labels
correct_predictions = np.sum(outputs == labels)

# Print the results
print("Inputs:", inputs)
print("Labels (Actual Outputs):", labels)
print("Predicted Outputs:", outputs)
print("Correct Predictions:", correct_predictions)

Inputs: [[0 0]
 [0 1]
 [1 0]
 [1 1]]
Labels (Actual Outputs): [0 0 0 1]
Predicted Outputs: [0, 0, 0, 1]
Correct Predictions: 4


In [5]:
# AND gate (optimized)

inputs = np.array([[0, 0],
                   [0, 1],
                   [1, 0],
                   [1, 1]])
labels = np.array([0, 0, 0, 1])

weights = np.array([0.5, 0.5])

bias = [-0.7, -0.7, -0.7, -0.7]

def step_function(x, threshold=0):
    return np.where(x <= threshold, 0, 1)

outputs = np.dot(inputs, weights) + bias

final_outputs = step_function(outputs)

correct_predictions = np.sum(final_outputs == labels)

print("Inputs:", inputs)
print("Labels (Actual Outputs):", labels)
print("Predicted Outputs:", final_outputs)
print("Correct Predictions:", correct_predictions)

Inputs: [[0 0]
 [0 1]
 [1 0]
 [1 1]]
Labels (Actual Outputs): [0 0 0 1]
Predicted Outputs: [0 0 0 1]
Correct Predictions: 4


In [6]:
# Define the inputs and corresponding labels for the 2-input AND gate (random weights and biases)

inputs = np.array([[0, 0],
                   [0, 1],
                   [1, 0],
                   [1, 1]])

labels = np.array([0, 0, 0, 1])

# Define the range for random initialization
weight_range = (-1, 1)
bias_range = (-1, 1)

# Randomly initialize the weights and bias within the defined range
weights = np.random.uniform(low=weight_range[0], high=weight_range[1], size=(2,))
bias = np.random.uniform(low=bias_range[0], high=bias_range[1])

# Define the activation function (step function)
def step_function(x):
    return 0 if x <= 0 else 1

# Perform the forward pass to compute the outputs
outputs = []
for input_row in inputs:
    weighted_sum = np.dot(input_row, weights) + bias
    output = step_function(weighted_sum)
    outputs.append(output)

# Compare the predicted outputs with the actual labels
correct_predictions = np.sum(outputs == labels)

# Print the results
print("Random Weights:", weights)
print("Random Bias:", bias)
print("Inputs:", inputs)
print("Labels (Actual Outputs):", labels)
print("Predicted Outputs:", outputs)
print("Correct Predictions:", correct_predictions)

Random Weights: [ 0.63166625 -0.55111886]
Random Bias: -0.5523647703547538
Inputs: [[0 0]
 [0 1]
 [1 0]
 [1 1]]
Labels (Actual Outputs): [0 0 0 1]
Predicted Outputs: [0, 0, 1, 0]
Correct Predictions: 2


In [7]:
# Define the inputs and corresponding labels for the 3-input AND gate

inputs = np.array([[0, 0, 0],
                   [0, 0, 1],
                   [0, 1, 0],
                   [0, 1, 1],
                   [1, 0, 0],
                   [1, 0, 1],
                   [1, 1, 0],
                   [1, 1, 1]])

labels = np.array([0, 0, 0, 0, 0, 0, 0, 1])

# Define the weights and bias for the neural network
weights = np.array([1, 1, 1])
bias = -2.5

# Define the activation function (step function)
def step_function(x):
    return 0 if x <= 0 else 1

# Perform the forward pass to compute the outputs
outputs = []
for input_row in inputs:
    weighted_sum = np.dot(input_row, weights) + bias
    output = step_function(weighted_sum)
    outputs.append(output)

# print(len(labels))

# Compare the predicted outputs with the actual labels
correct_predictions = np.sum(np.array(outputs) == labels)

# Print the results
print("Inputs:", inputs)
print("Labels (Actual Outputs):", labels)
print("Predicted Outputs:", outputs)
print("Correct Predictions:", correct_predictions)

Inputs: [[0 0 0]
 [0 0 1]
 [0 1 0]
 [0 1 1]
 [1 0 0]
 [1 0 1]
 [1 1 0]
 [1 1 1]]
Labels (Actual Outputs): [0 0 0 0 0 0 0 1]
Predicted Outputs: [0, 0, 0, 0, 0, 0, 0, 1]
Correct Predictions: 8


In [8]:
# Solve OR gate problem using neural network

# Define the inputs and corresponding labels for the 2-input OR gate
inputs = np.array([[0, 0],
                   [0, 1],
                   [1, 0],
                   [1, 1]])

labels = np.array([0, 1, 1, 1]) 

# Define the weights and bias for the neural network
weights = np.array([0.5, 0.5]) 
bias = -0.2 

# Define the activation function (step function)
def step_function(x):
    return 0 if x <= 0 else 1

# Perform the forward pass to compute the outputs
outputs = []
for input_row in inputs:
    weighted_sum = np.dot(input_row, weights) + bias
    output = step_function(weighted_sum)
    outputs.append(output)

# Compare the predicted outputs with the actual labels
correct_predictions = np.sum(outputs == labels)

# Print the results
print("Inputs:", inputs)
print("Labels (Actual Outputs):", labels)
print("Predicted Outputs:", outputs)
print("Correct Predictions:", correct_predictions)

Inputs: [[0 0]
 [0 1]
 [1 0]
 [1 1]]
Labels (Actual Outputs): [0 1 1 1]
Predicted Outputs: [0, 1, 1, 1]
Correct Predictions: 4


In [9]:
# OR gate (optimized)

inputs = np.array([[0, 0],
                   [0, 1],
                   [1, 0],
                   [1, 1]])

labels = np.array([0, 1, 1, 1])

weights = np.array([0.5, 0.5])

bias = [-0.2, -0.2, -0.2, -0.2]

def step_function(x, threshold=0):
    return np.where(x <= threshold, 0, 1)

outputs = np.dot(inputs, weights) + bias

final_outputs = step_function(outputs)

correct_predictions = np.sum(final_outputs == labels)

print("Inputs:", inputs)
print("Labels (Actual Outputs):", labels)
print("Predicted Outputs:", final_outputs)
print("Correct Predictions:", correct_predictions)

Inputs: [[0 0]
 [0 1]
 [1 0]
 [1 1]]
Labels (Actual Outputs): [0 1 1 1]
Predicted Outputs: [0 1 1 1]
Correct Predictions: 4


In [10]:
# Define the inputs and corresponding labels for the 2-input OR gate (random weights and biases)

inputs = np.array([[0, 0],
                   [0, 1],
                   [1, 0],
                   [1, 1]])

labels = np.array([0, 1, 1, 1])

# Define the range for random initialization
weight_range = (-1, 1)
bias_range = (-1, 1)

# Randomly initialize the weights and bias within the defined range
weights = np.random.uniform(low=weight_range[0], high=weight_range[1], size=(2,))
bias = np.random.uniform(low=bias_range[0], high=bias_range[1])

# Define the activation function (step function)
def step_function(x):
    return 0 if x <= 0 else 1


# Perform the forward pass to compute the outputs
outputs = []
for input_row in inputs:
    weighted_sum = np.dot(input_row, weights) + bias
    output = step_function(weighted_sum)
    outputs.append(output)

# Compare the predicted outputs with the actual labels
correct_predictions = np.sum(np.array(outputs) == labels)

# Print the results
print("Random Weights:", weights)
print("Random Bias:", bias)
print("Inputs:", inputs)
print("Labels (Actual Outputs):", labels)
print("Predicted Outputs:", outputs)
print("Correct Predictions:", correct_predictions)

Random Weights: [0.07394885 0.18587987]
Random Bias: 0.16017241567562235
Inputs: [[0 0]
 [0 1]
 [1 0]
 [1 1]]
Labels (Actual Outputs): [0 1 1 1]
Predicted Outputs: [1, 1, 1, 1]
Correct Predictions: 3


In [11]:
# Define the inputs and corresponding labels for the 3-input OR gate

inputs = np.array([[0, 0, 0],
                   [0, 0, 1],
                   [0, 1, 0],
                   [0, 1, 1],
                   [1, 0, 0],
                   [1, 0, 1],
                   [1, 1, 0],
                   [1, 1, 1]])

labels = np.array([0, 1, 1, 1, 1, 1, 1, 1])

# Define the weights and bias for the neural network
weights = np.array([1, 1, 1])
bias = -0.5

# Define the activation function (step function)
def step_function(x):
    return 0 if x <= 0 else 1

# Perform the forward pass to compute the outputs
outputs = []
for input_row in inputs:
    weighted_sum = np.dot(input_row, weights) + bias
    output = step_function(weighted_sum)
    outputs.append(output)

# print(len(labels))

# Compare the predicted outputs with the actual labels
correct_predictions = np.sum(np.array(outputs) == labels)

# Print the results
print("Inputs:", inputs)
print("Labels (Actual Outputs):", labels)
print("Predicted Outputs:", outputs)
print("Correct Predictions:", correct_predictions)

Inputs: [[0 0 0]
 [0 0 1]
 [0 1 0]
 [0 1 1]
 [1 0 0]
 [1 0 1]
 [1 1 0]
 [1 1 1]]
Labels (Actual Outputs): [0 1 1 1 1 1 1 1]
Predicted Outputs: [0, 1, 1, 1, 1, 1, 1, 1]
Correct Predictions: 8


In [12]:
# Solve NOT gate problem using neural network

# Define the inputs and corresponding labels for the NOT gate
inputs = np.array([0,
                   1])

labels = np.array([1, 0])

# Define the weight and bias for the neural network
weight = -1
bias = 0.5

# Define the activation function (step function)
def step_function(x):
    return 0 if x <= 0 else 1

# Perform the forward pass to compute the outputs
outputs = []
for input_row in inputs:
    weighted_sum = np.dot(input_row, weight) + bias
    output = step_function(weighted_sum)
    outputs.append(output)

# Compare the predicted outputs with the actual labels
correct_predictions = np.sum(np.array(outputs) == labels)

# Print the results
print("Inputs:", inputs.flatten())
print("Labels (Actual Outputs):", labels)
print("Predicted Outputs:", outputs)
print("Correct Predictions:", correct_predictions)

Inputs: [0 1]
Labels (Actual Outputs): [1 0]
Predicted Outputs: [1, 0]
Correct Predictions: 2


In [13]:
# NOT gate (optimized)

inputs = np.array([[0],
                   [1]])

labels = np.array([1, 0])

weights = np.array([-1])

bias = [0.5]

def step_function(x, threshold=0):
    return np.where(x <= threshold, 0, 1)

outputs = np.dot(inputs, weights) + bias

final_outputs = step_function(outputs)

correct_predictions = np.sum(final_outputs == labels)

print("Inputs:", inputs)
print("Labels (Actual Outputs):", labels)
print("Predicted Outputs:", final_outputs)
print("Correct Predictions:", correct_predictions)

Inputs: [[0]
 [1]]
Labels (Actual Outputs): [1 0]
Predicted Outputs: [1 0]
Correct Predictions: 2


In [14]:
# Define the inputs and corresponding labels for the NOT gate (random weights and biases)

inputs = np.array([[0],
                   [1]])

labels = np.array([1, 0])  # Output for NOT gate: 1 when input is 0, and 0 when input is 1

# Define the range for random initialization
weight_range = (-2, 2)
bias_range = (-1, 1)

# Randomly initialize the weight and bias within the defined range
weight = np.random.uniform(low=weight_range[0], high=weight_range[1])
bias = np.random.uniform(low=bias_range[0], high=bias_range[1])

# Define the activation function (step function)
def step_function(x):
    return 0 if x <= 0 else 1

# Perform the forward pass to compute the outputs
outputs = []
for input_row in inputs:
    weighted_sum = np.dot(input_row, weight) + bias
    output = step_function(weighted_sum)
    outputs.append(output)

# Compare the predicted outputs with the actual labels
correct_predictions = np.sum(np.array(outputs) == labels)

# Print the results
print("Random Weight:", weight)
print("Random Bias:", bias)
print("Inputs:", inputs.flatten())
print("Labels (Actual Outputs):", labels)
print("Predicted Outputs:", outputs)
print("Correct Predictions:", correct_predictions)

Random Weight: -1.6340526504089805
Random Bias: 0.7549217252607607
Inputs: [0 1]
Labels (Actual Outputs): [1 0]
Predicted Outputs: [1, 0]
Correct Predictions: 2


In [15]:
# Define the inputs and corresponding labels for the 2-input NAND gate

inputs = np.array([[0, 0],
                   [0, 1],
                   [1, 0],
                   [1, 1]])

labels = np.array([1, 1, 1, 0])

# Define the weights and bias for the neural network
weights = np.array([-0.5, -0.5])
bias = 0.7

# Define the activation function (step function)
def step_function(x):
    return 0 if x <= 0 else 1

# Perform the forward pass to compute the outputs
outputs = []
for input_row in inputs:
    weighted_sum = np.dot(input_row, weights) + bias
    output = step_function(weighted_sum)
    outputs.append(output)

# Compare the predicted outputs with the actual labels
correct_predictions = np.sum(np.array(outputs) == labels)

# Print the results
print("Inputs:", inputs)
print("Labels (Actual Outputs):", labels)
print("Predicted Outputs:", outputs)
print("Correct Predictions:", correct_predictions)

Inputs: [[0 0]
 [0 1]
 [1 0]
 [1 1]]
Labels (Actual Outputs): [1 1 1 0]
Predicted Outputs: [1, 1, 1, 0]
Correct Predictions: 4


In [16]:
# NAND gate (optimized)

inputs = np.array([[0, 0],
                   [0, 1],
                   [1, 0],
                   [1, 1]])

labels = np.array([1, 1, 1, 0])

weights = np.array([-0.5, -0.5])

bias = [0.7, 0.7, 0.7, 0.7]

def step_function(x, threshold=0):
    return np.where(x <= threshold, 0, 1)

outputs = np.dot(inputs, weights) + bias

final_outputs = step_function(outputs)

correct_predictions = np.sum(final_outputs == labels)

print("Inputs:", inputs)
print("Labels (Actual Outputs):", labels)
print("Predicted Outputs:", final_outputs)
print("Correct Predictions:", correct_predictions)

Inputs: [[0 0]
 [0 1]
 [1 0]
 [1 1]]
Labels (Actual Outputs): [1 1 1 0]
Predicted Outputs: [1 1 1 0]
Correct Predictions: 4


In [17]:
# Define the inputs and corresponding labels for the 2-input NAND gate (random weights and biases)
inputs = np.array([[0, 0],
                   [0, 1],
                   [1, 0],
                   [1, 1]])

labels = np.array([1, 1, 1, 0])

# Define the range for random initialization
weight_range = (-1, 1)
bias_range = (-1, 1)

# Randomly initialize the weights and bias within the defined range
weights = np.random.uniform(low=weight_range[0], high=weight_range[1], size=(2,))
bias = np.random.uniform(low=bias_range[0], high=bias_range[1])

# Define the activation function (step function)
def step_function(x):
    return 0 if x <= 0 else 1

# Perform the forward pass to compute the outputs
outputs = []
for input_row in inputs:
    weighted_sum = np.dot(input_row, weights) + bias
    output = step_function(weighted_sum)
    outputs.append(output)

# Compare the predicted outputs with the actual labels
correct_predictions = np.sum(np.array(outputs) == labels)

# Print the results
print("Random Weights:", weights)
print("Random Bias:", bias)
print("Inputs:", inputs)
print("Labels (Actual Outputs):", labels)
print("Predicted Outputs:", outputs)
print("Correct Predictions:", correct_predictions)

Random Weights: [-0.46879991 -0.74097016]
Random Bias: 0.7774961597379544
Inputs: [[0 0]
 [0 1]
 [1 0]
 [1 1]]
Labels (Actual Outputs): [1 1 1 0]
Predicted Outputs: [1, 1, 1, 0]
Correct Predictions: 4


In [18]:
# Define the inputs and corresponding labels for the 3-input NAND gate
inputs = np.array([[0, 0, 0],
                   [0, 0, 1],
                   [0, 1, 0],
                   [0, 1, 1],
                   [1, 0, 0],
                   [1, 0, 1],
                   [1, 1, 0],
                   [1, 1, 1]])

labels = np.array([1, 1, 1, 1, 1, 1, 1, 0])

# Define the weights and bias for the neural network
weights = np.array([-1, -1, -1])
bias = 2.5

# Define the activation function (step function)
def step_function(x):
    return 0 if x <= 0 else 1

# Perform the forward pass to compute the outputs
outputs = []
for input_row in inputs:
    weighted_sum = np.dot(input_row, weights) + bias
    output = step_function(weighted_sum)
    outputs.append(output)

# Compare the predicted outputs with the actual labels
correct_predictions = np.sum(np.array(outputs) == labels)

# Print the results
print("Inputs:", inputs)
print("Labels (Actual Outputs):", labels)
print("Predicted Outputs:", outputs)
print("Correct Predictions:", correct_predictions)

Inputs: [[0 0 0]
 [0 0 1]
 [0 1 0]
 [0 1 1]
 [1 0 0]
 [1 0 1]
 [1 1 0]
 [1 1 1]]
Labels (Actual Outputs): [1 1 1 1 1 1 1 0]
Predicted Outputs: [1, 1, 1, 1, 1, 1, 1, 0]
Correct Predictions: 8


In [19]:
# Define the inputs and corresponding labels for the 2-input NOR gate
inputs = np.array([[0, 0],
                   [0, 1],
                   [1, 0],
                   [1, 1]])

labels = np.array([1, 0, 0, 0])

# Define the weights and bias for the neural network
weights = np.array([-0.5, -0.5])
bias = 0.5

# Define the activation function (step function)
def step_function(x):
    return 0 if x <= 0 else 1

# Perform the forward pass to compute the outputs
outputs = []
for input_row in inputs:
    weighted_sum = np.dot(input_row, weights) + bias
    output = step_function(weighted_sum)
    outputs.append(output)

# Compare the predicted outputs with the actual labels
correct_predictions = np.sum(np.array(outputs) == labels)

# Print the results
print("Inputs:", inputs)
print("Labels (Actual Outputs):", labels)
print("Predicted Outputs:", outputs)
print("Correct Predictions:", correct_predictions)

Inputs: [[0 0]
 [0 1]
 [1 0]
 [1 1]]
Labels (Actual Outputs): [1 0 0 0]
Predicted Outputs: [1, 0, 0, 0]
Correct Predictions: 4


In [20]:
# NOR gate (optimized)

inputs = np.array([[0, 0],
                   [0, 1],
                   [1, 0],
                   [1, 1]])

labels = np.array([1, 0, 0, 0])

weights = np.array([-0.5, -0.5])

bias = [0.5, 0.5, 0.5, 0.5]

def step_function(x, threshold=0):
    return np.where(x <= threshold, 0, 1)

outputs = np.dot(inputs, weights) + bias

final_outputs = step_function(outputs)

correct_predictions = np.sum(final_outputs == labels)

print("Inputs:", inputs)
print("Labels (Actual Outputs):", labels)
print("Predicted Outputs:", final_outputs)
print("Correct Predictions:", correct_predictions)

Inputs: [[0 0]
 [0 1]
 [1 0]
 [1 1]]
Labels (Actual Outputs): [1 0 0 0]
Predicted Outputs: [1 0 0 0]
Correct Predictions: 4


In [21]:
# Define the inputs and corresponding labels for the 2-input NOR gate (random weights and biases)
inputs = np.array([[0, 0],
                   [0, 1],
                   [1, 0],
                   [1, 1]])

labels = np.array([1, 0, 0, 0])  # Output for NOR gate: 1, 0, 0, 0

# Define the range for random initialization
weight_range = (-1, 1)
bias_range = (-1, 1)

# Randomly initialize the weights and bias within the defined range
weights = np.random.uniform(low=weight_range[0], high=weight_range[1], size=(2,))
bias = np.random.uniform(low=bias_range[0], high=bias_range[1])

# Define the activation function (step function)
def step_function(x):
    return 0 if x <= 0 else 1

# Perform the forward pass to compute the outputs
outputs = []
for input_row in inputs:
    weighted_sum = np.dot(input_row, weights) + bias
    output = step_function(weighted_sum)
    outputs.append(output)

# Compare the predicted outputs with the actual labels
correct_predictions = np.sum(np.array(outputs) == labels)

# Print the results
print("Random Weights:", weights)
print("Random Bias:", bias)
print("Inputs:", inputs)
print("Labels (Actual Outputs):", labels)
print("Predicted Outputs:", outputs)
print("Correct Predictions:", correct_predictions)

Random Weights: [0.911303   0.72425523]
Random Bias: 0.6190321494497562
Inputs: [[0 0]
 [0 1]
 [1 0]
 [1 1]]
Labels (Actual Outputs): [1 0 0 0]
Predicted Outputs: [1, 1, 1, 1]
Correct Predictions: 1


In [22]:
# Define the inputs and corresponding labels for the 3-input NOR gate
inputs = np.array([[0, 0, 0],
                   [0, 0, 1],
                   [0, 1, 0],
                   [0, 1, 1],
                   [1, 0, 0],
                   [1, 0, 1],
                   [1, 1, 0],
                   [1, 1, 1]])

labels = np.array([1, 0, 0, 0, 0, 0, 0, 0])  # Output for NOR gate: 1, 0, 0, 0, 0, 0, 0, 0

# Define the weights and bias for the neural network
weights = np.array([-1, -1, -1])
bias = 0.5

# Define the activation function (step function)
def step_function(x):
    return 0 if x <= 0 else 1

# Perform the forward pass to compute the outputs
outputs = []
for input_row in inputs:
    weighted_sum = np.dot(input_row, weights) + bias
    output = step_function(weighted_sum)
    outputs.append(output)

# Compare the predicted outputs with the actual labels
correct_predictions = np.sum(np.array(outputs) == labels)

# Print the results
print("Inputs:", inputs)
print("Labels (Actual Outputs):", labels)
print("Predicted Outputs:", outputs)
print("Correct Predictions:", correct_predictions)

Inputs: [[0 0 0]
 [0 0 1]
 [0 1 0]
 [0 1 1]
 [1 0 0]
 [1 0 1]
 [1 1 0]
 [1 1 1]]
Labels (Actual Outputs): [1 0 0 0 0 0 0 0]
Predicted Outputs: [1, 0, 0, 0, 0, 0, 0, 0]
Correct Predictions: 8
