In [1]:
#a simple neural network with one output neuron, four inputs and weights, and bias

inputs = [1.0, 2.0, 3.0, 2.5]
weights = [0.2, 0.8, -0.5, 1.0]
bias = 2.0
output = (inputs[0] * weights[0] + inputs[1] * weights[1] + inputs[2] * weights[2] + inputs[3] * weights[3] + bias)
print("Output with initial weights and bias:", output)

Output with initial weights and bias: 4.8


In [2]:
# Design the previous example of neural network by adjusting weights and bias randomly

import random
for i in range(len(weights)):
    weights[i] += random.uniform(-0.5, 0.5)
bias += random.uniform(-0.5, 0.5)

# Calculate output with adjusted weights and bias
output = (inputs[0] * weights[0] + inputs[1] * weights[1] + inputs[2] * weights[2] + inputs[3] * weights[3] + bias)
print("Output with adjusted weights and bias:", output)

Output with adjusted weights and bias: 5.0724367992094805


In [3]:
# A fully connected neural network — every neuron in the current layer has connections to every neuron from the previous layer.

inputs = [1, 2, 3, 2.5]
weights1 = [0.2, 0.8, -0.5, 1]
weights2 = [0.5, -0.91, 0.26, -0.5]
weights3 = [-0.26, -0.27, 0.17, 0.87]
bias1 = 2
bias2 = 3
bias3 = 0.5

outputs = [
    # Neuron 1:
    inputs[0] * weights1[0] + inputs[1] * weights1[1] + inputs[2] * weights1[2] + inputs[3] * weights1[3] + bias1,

    # Neuron 2:
    inputs[0] * weights2[0] + inputs[1] * weights2[1] + inputs[2] * weights2[2] + inputs[3] * weights2[3] + bias2,

    # Neuron 3:
    inputs[0] * weights3[0] + inputs[1] * weights3[1] + inputs[2] * weights3[2] + inputs[3] * weights3[3] + bias3]

print("Output:", outputs)

Output: [4.8, 1.21, 2.385]


In [4]:
# A fully connected neural network — every neuron in the current layer has connections to every neuron from the previous layer.
# You have 4 input neurons, one hidden layer consisting of 3 neurons and one output neuron. You should adust weights and biases randomly.

inputs = [1, 2, 3, 2.5]

# Randomly initialize weights and biases for the hidden layer
hidden_weights = [[random.uniform(-1, 1) for _ in range(4)] for _ in range(3)]
hidden_biases = [random.uniform(-1, 1) for _ in range(3)]

# Randomly initialize weights and bias for the output layer
output_weights = [random.uniform(-1, 1) for _ in range(3)]
output_bias = random.uniform(-1, 1)

# Calculate outputs for the hidden layer
hidden_outputs = [
    sum([inputs[i] * hidden_weights[j][i] for i in range(4)]) + hidden_biases[j]
    for j in range(3)
]

# Calculate output for the output layer
output = sum([hidden_outputs[j] * output_weights[j] for j in range(3)]) + output_bias

print("Output:", output)

Output: -4.263782339555571


In [5]:
# Using loop option to get the weights, inputs and biases then feed into the neurons.

inputs = [1, 2, 3, 2.5]
weights = [
           [0.2, 0.8, -0.5, 1],
           [0.5, -0.91, 0.26, -0.5],
           [-0.26, -0.27, 0.17, 0.87]
          ]
biases = [2, 3, 0.5]

# Output of the current layer
layer_outputs = []

# For each neuron
for neuron_weights, neuron_bias in zip(weights, biases):
    # Zeroed output of the given neuron
    neuron_output = 0

    # For each input and weight to the neuron
    for n_input, weight in zip(inputs, neuron_weights):
        # Multiply this input by the associated weight
        # and add to the neuron's output variable

        neuron_output += n_input * weight

    # Add bias
    neuron_output += neuron_bias

    # Put the neuron's result into the layer's output list
    layer_outputs.append(neuron_output)

#print(layer_outputs)
weight_out = [0.2, 0.8, -0.5]
bias_out = 0.5
final_output = (layer_outputs[0] * weight_out[0] + layer_outputs[1] * weight_out[1] + layer_outputs[2] * weight_out[2]) + bias_out
print("Output:", final_output)

Output: 1.2355


In [6]:
# Using numpy library to calculate dot product in the neural network.

import numpy as np

inputs = [1.0, 2.0, 3.0, 2.5]
weights = [0.2, 0.8, -0.5, 1.0]
bias = 2.0

outputs = np.dot(weights, inputs) + bias
print("Output:", outputs)

Output: 4.8


In [7]:
inputs = [1, 2, 3, 2.5]
weights = [
    [0.2, 0.8, -0.5, 1],
    [0.5, -0.91, 0.26, -0.5],
    [-0.26, -0.27, 0.17, 0.87]
]
biases = [2, 3, 0.5]

outputs = np.dot(weights, inputs) + biases
# or
# outputs = np.dot(inputs, np.array(weights).T) + biases

print("Output:", outputs)

Output: [4.8   1.21  2.385]


In [8]:
# Same code while multiplying the inputs with transpose of the weights to adjust the matrix row column multiplication concept

inputs = np.array([1, 2, 3, 2.5])
weights = np.array([
    [0.2, 0.8, -0.5, 1],
    [0.5, -0.91, 0.26, -0.5],
    [-0.26, -0.27, 0.17, 0.87]
])
biases = np.array([2, 3, 0.5])

outputs = np.dot(inputs, weights.T) + biases
print("Output:", outputs)

Output: [4.8   1.21  2.385]


In [9]:
# Take inputs containing 3 samples with 4 features, and 3 neurons with weights and biases, respectively.
# Then print the outputs of the neorons.

# Define inputs (3 samples with 4 features each)
inputs = np.array([
    [1, 2, 3, 2.5],
    [2.0, 5.0, -1.0, 2.0],
    [-1.5, 2.7, 3.3, -0.8]
])

# Define weights (3 neurons with 4 weights each)
weights = np.array([
    [0.2, 0.8, -0.5, 1],
    [0.5, -0.91, 0.26, -0.5],
    [-0.26, -0.27, 0.17, 0.87]
])

# Define biases (3 biases, one for each neuron)
biases = np.array([2, 3, 0.5])

outputs = np.dot(inputs, weights.T) + biases
print(outputs)

[[ 4.8    1.21   2.385]
 [ 8.9   -1.81   0.2  ]
 [ 1.41   1.051  0.026]]


In [10]:
# inputs-batch with weights and then transpose them to calculate dot product.

# inputs = [[1.0, 2.0, 3.0, 2.5], [2.0, 4.0, 1.5, 2.0], [0.5, 1.5, 2.0, 3.5]]
# weights = [[0.2, 0.8, -0.5, 1.0], [0.5, -0.9, 0.3, -0.7], [-0.1, 0.6, -0.3, 0.9]]

inputs = np.array([[1.0, 2.0, 3.0, 2.5],
                   [2.0, 4.0, 1.5, 2.0],
                   [0.5, 1.5, 2.0, 3.5],
                   [1.0, 2.0, 3.0, 2.5],
                   [0.5, 1.5, 2.0, 3.5]])

weights = np.array([[0.2, 0.8, -0.5, 1.0],
                    [0.5, -0.9, 0.3, -0.7],
                    [-0.1, 0.6, -0.3, 0.9]])

biases = np.array([2.0, 1.0, -0.5])

outputs = np.dot(inputs, weights.T)+biases
print(outputs)

[[ 4.8  -1.15  1.95]
 [ 6.85 -2.55  3.05]
 [ 5.8  -1.95  2.9 ]
 [ 4.8  -1.15  1.95]
 [ 5.8  -1.95  2.9 ]]


In [11]:
# Two hidden layers with four neurons at the first layer and three in the second.

inputs = [[1, 2, 3, 2.5],
          [2., 5., -1., 2],
          [-1.5, 2.7, 3.3, -0.8],
          [3, 2, 1.7, -0.5]
          ]

weights = [[0.2, 0.8, -0.5, 1],
           [0.5, -0.91, 0.26, -0.5],
           [-0.26, -0.27, 0.17, 0.87]]

biases = [2, 3, 0.5]

weights2 = [[0.1, -0.14, 0.5],
            [-0.5, 0.12, -0.33],
            [-0.44, 0.73, -0.13]]

biases2 = [-1, 2, -0.5]

layer1_outputs = np.dot(inputs, np.array(weights).T) + biases

layer2_outputs = np.dot(layer1_outputs, np.array(weights2).T) + biases2

print(layer2_outputs)

[[ 0.5031  -1.04185 -2.03875]
 [ 0.2434  -2.7332  -5.7633 ]
 [-0.99314  1.41254 -0.35655]
 [-1.67008  1.29842  0.83314]]


In [12]:
# Sigmoidal activation function

def sigmoid(x):
    return 1 / (1 + np.exp(-x))

# Example usage
x = np.array([0.5, -1.0, 2.0])
output = sigmoid(x)
print(output)

[0.62245933 0.26894142 0.88079708]


In [13]:
# Rectified Linear Unit (ReLU) activation function

def relu(x):
    return np.maximum(0, x)

# Example usage
x = np.array([-2.0, -1.0, 0.0, 1.0, 2.0])
output = relu(x)
print(output)

[0. 0. 0. 1. 2.]


In [14]:
# Step function

def step_function(x, threshold=0):
    if x <= threshold:
        return 0
    else:
        return 1

# Example usage
x = 0.5
output = step_function(x)
print(output)

1


In [15]:
# Step function

def step_function(x, threshold=0):
    return np.where(x <= threshold, 0, 1)

# Example usage
x = np.array([-2.0, -1.0, 0.0, 1.0, 2.0])
output = step_function(x)
print(output)

[0 0 0 1 1]


In [16]:
# Solve AND gate problem using neural network

# Define the inputs and corresponding labels for the 2-input AND gate
inputs = np.array([[0, 0],
                   [0, 1],
                   [1, 0],
                   [1, 1]])

labels = np.array([0, 0, 0, 1])

# Define the weights and biases for the neural network
weights = np.array([0.5, 0.5])
bias = -0.7

# Define the activation function (step function)
def step_function(x):
    return 0 if x <= 0 else 1

# Perform the forward pass to compute the outputs
outputs = []
for input_row in inputs:
    weighted_sum = np.dot(input_row, weights) + bias
    output = step_function(weighted_sum)
    outputs.append(output)

# Compare the predicted outputs with the actual labels
correct_predictions = np.sum(outputs == labels)

# Print the results
print("Inputs:", inputs)
print("Labels (Actual Outputs):", labels)
print("Predicted Outputs:", outputs)
print("Correct Predictions:", correct_predictions)

Inputs: [[0 0]
 [0 1]
 [1 0]
 [1 1]]
Labels (Actual Outputs): [0 0 0 1]
Predicted Outputs: [0, 0, 0, 1]
Correct Predictions: 4


In [17]:
# Define the inputs and corresponding labels for the 2-input AND gate (random weights and biases)

inputs = np.array([[0, 0],
                   [0, 1],
                   [1, 0],
                   [1, 1]])

labels = np.array([0, 0, 0, 1])

# Define the range for random initialization
weight_range = (-1, 1)
bias_range = (-1, 1)

# Randomly initialize the weights and bias within the defined range
weights = np.random.uniform(low=weight_range[0], high=weight_range[1], size=(2,))
bias = np.random.uniform(low=bias_range[0], high=bias_range[1])

# Define the activation function (step function)
def step_function(x):
    return 0 if x <= 0 else 1

# Perform the forward pass to compute the outputs
outputs = []
for input_row in inputs:
    weighted_sum = np.dot(input_row, weights) + bias
    output = step_function(weighted_sum)
    outputs.append(output)

# Compare the predicted outputs with the actual labels
correct_predictions = np.sum(outputs == labels)

# Print the results
print("Random Weights:", weights)
print("Random Bias:", bias)
print("Inputs:", inputs)
print("Labels (Actual Outputs):", labels)
print("Predicted Outputs:", outputs)
print("Correct Predictions:", correct_predictions)

Random Weights: [-0.66113658  0.57488481]
Random Bias: 0.8987828534282349
Inputs: [[0 0]
 [0 1]
 [1 0]
 [1 1]]
Labels (Actual Outputs): [0 0 0 1]
Predicted Outputs: [1, 1, 1, 1]
Correct Predictions: 1


In [18]:
# Define the inputs and corresponding labels for the 3-input AND gate

inputs = np.array([[0, 0, 0],
                   [0, 0, 1],
                   [0, 1, 0],
                   [0, 1, 1],
                   [1, 0, 0],
                   [1, 0, 1],
                   [1, 1, 0],
                   [1, 1, 1]])

labels = np.array([0, 0, 0, 0, 0, 0, 0, 1])

# Define the weights and bias for the neural network
weights = np.array([1, 1, 1])
bias = -2.5

# Define the activation function (step function)
def step_function(x):
    return 0 if x <= 0 else 1

# Perform the forward pass to compute the outputs
outputs = []
for input_row in inputs:
    weighted_sum = np.dot(input_row, weights) + bias
    output = step_function(weighted_sum)
    outputs.append(output)

# print(len(labels))

# Compare the predicted outputs with the actual labels
correct_predictions = np.sum(np.array(outputs) == labels)

# Print the results
print("Inputs:", inputs)
print("Labels (Actual Outputs):", labels)
print("Predicted Outputs:", outputs)
print("Correct Predictions:", correct_predictions)

Inputs: [[0 0 0]
 [0 0 1]
 [0 1 0]
 [0 1 1]
 [1 0 0]
 [1 0 1]
 [1 1 0]
 [1 1 1]]
Labels (Actual Outputs): [0 0 0 0 0 0 0 1]
Predicted Outputs: [0, 0, 0, 0, 0, 0, 0, 1]
Correct Predictions: 8


In [19]:
# Solve OR gate problem using neural network

# Define the inputs and corresponding labels for the 2-input OR gate
inputs = np.array([[0, 0],
                   [0, 1],
                   [1, 0],
                   [1, 1]])

labels = np.array([0, 1, 1, 1]) 

# Define the weights and bias for the neural network
weights = np.array([0.5, 0.5]) 
bias = -0.2 

# Define the activation function (step function)
def step_function(x):
    return 0 if x <= 0 else 1

# Perform the forward pass to compute the outputs
outputs = []
for input_row in inputs:
    weighted_sum = np.dot(input_row, weights) + bias
    output = step_function(weighted_sum)
    outputs.append(output)

# Compare the predicted outputs with the actual labels
correct_predictions = np.sum(outputs == labels)

# Print the results
print("Inputs:", inputs)
print("Labels (Actual Outputs):", labels)
print("Predicted Outputs:", outputs)
print("Correct Predictions:", correct_predictions)

Inputs: [[0 0]
 [0 1]
 [1 0]
 [1 1]]
Labels (Actual Outputs): [0 1 1 1]
Predicted Outputs: [0, 1, 1, 1]
Correct Predictions: 4


In [20]:
# Define the inputs and corresponding labels for the 2-input OR gate (random weights and biases)

inputs = np.array([[0, 0],
                   [0, 1],
                   [1, 0],
                   [1, 1]])

labels = np.array([0, 1, 1, 1])

# Define the range for random initialization
weight_range = (-1, 1)
bias_range = (-1, 1)

# Randomly initialize the weights and bias within the defined range
weights = np.random.uniform(low=weight_range[0], high=weight_range[1], size=(2,))
bias = np.random.uniform(low=bias_range[0], high=bias_range[1])

# Define the activation function (step function)
def step_function(x):
    return 0 if x <= 0 else 1


# Perform the forward pass to compute the outputs
outputs = []
for input_row in inputs:
    weighted_sum = np.dot(input_row, weights) + bias
    output = step_function(weighted_sum)
    outputs.append(output)

# Compare the predicted outputs with the actual labels
correct_predictions = np.sum(np.array(outputs) == labels)

# Print the results
print("Random Weights:", weights)
print("Random Bias:", bias)
print("Inputs:", inputs)
print("Labels (Actual Outputs):", labels)
print("Predicted Outputs:", outputs)
print("Correct Predictions:", correct_predictions)

Random Weights: [-0.6553367  -0.74693924]
Random Bias: -0.33252453181317554
Inputs: [[0 0]
 [0 1]
 [1 0]
 [1 1]]
Labels (Actual Outputs): [0 1 1 1]
Predicted Outputs: [0, 0, 0, 0]
Correct Predictions: 1


In [21]:
# Define the inputs and corresponding labels for the 3-input OR gate

inputs = np.array([[0, 0, 0],
                   [0, 0, 1],
                   [0, 1, 0],
                   [0, 1, 1],
                   [1, 0, 0],
                   [1, 0, 1],
                   [1, 1, 0],
                   [1, 1, 1]])

labels = np.array([0, 1, 1, 1, 1, 1, 1, 1])

# Define the weights and bias for the neural network
weights = np.array([1, 1, 1])
bias = -0.5

# Define the activation function (step function)
def step_function(x):
    return 0 if x <= 0 else 1

# Perform the forward pass to compute the outputs
outputs = []
for input_row in inputs:
    weighted_sum = np.dot(input_row, weights) + bias
    output = step_function(weighted_sum)
    outputs.append(output)

# print(len(labels))

# Compare the predicted outputs with the actual labels
correct_predictions = np.sum(np.array(outputs) == labels)

# Print the results
print("Inputs:", inputs)
print("Labels (Actual Outputs):", labels)
print("Predicted Outputs:", outputs)
print("Correct Predictions:", correct_predictions)

Inputs: [[0 0 0]
 [0 0 1]
 [0 1 0]
 [0 1 1]
 [1 0 0]
 [1 0 1]
 [1 1 0]
 [1 1 1]]
Labels (Actual Outputs): [0 1 1 1 1 1 1 1]
Predicted Outputs: [0, 1, 1, 1, 1, 1, 1, 1]
Correct Predictions: 8


In [22]:
# Solve NOT gate problem using neural network

# Define the inputs and corresponding labels for the NOT gate
inputs = np.array([[0],
                   [1]])

labels = np.array([1, 0])

# Define the weight and bias for the neural network
weight = -1
bias = 0.5

# Define the activation function (step function)
def step_function(x):
    return 0 if x <= 0 else 1

# Perform the forward pass to compute the outputs
outputs = []
for input_row in inputs:
    weighted_sum = np.dot(input_row, weight) + bias
    output = step_function(weighted_sum)
    outputs.append(output)

# Compare the predicted outputs with the actual labels
correct_predictions = np.sum(np.array(outputs) == labels)

# Print the results
print("Inputs:", inputs.flatten())
print("Labels (Actual Outputs):", labels)
print("Predicted Outputs:", outputs)
print("Correct Predictions:", correct_predictions)

Inputs: [0 1]
Labels (Actual Outputs): [1 0]
Predicted Outputs: [1, 0]
Correct Predictions: 2


In [23]:
# Define the inputs and corresponding labels for the NOT gate (random weights and biases)

inputs = np.array([[0],
                   [1]])

labels = np.array([1, 0])  # Output for NOT gate: 1 when input is 0, and 0 when input is 1

# Define the range for random initialization
weight_range = (-2, 2)
bias_range = (-1, 1)

# Randomly initialize the weight and bias within the defined range
weight = np.random.uniform(low=weight_range[0], high=weight_range[1])
bias = np.random.uniform(low=bias_range[0], high=bias_range[1])

# Define the activation function (step function)
def step_function(x):
    return 0 if x <= 0 else 1

# Perform the forward pass to compute the outputs
outputs = []
for input_row in inputs:
    weighted_sum = np.dot(input_row, weight) + bias
    output = step_function(weighted_sum)
    outputs.append(output)

# Compare the predicted outputs with the actual labels
correct_predictions = np.sum(np.array(outputs) == labels)

# Print the results
print("Random Weight:", weight)
print("Random Bias:", bias)
print("Inputs:", inputs.flatten())
print("Labels (Actual Outputs):", labels)
print("Predicted Outputs:", outputs)
print("Correct Predictions:", correct_predictions)

Random Weight: -1.8513685019131971
Random Bias: -0.836535189637901
Inputs: [0 1]
Labels (Actual Outputs): [1 0]
Predicted Outputs: [0, 0]
Correct Predictions: 1
